// <auto-generated />
namespace Capstone_20130302.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ParentId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ParentId));
        
        string IMigrationMetadata.Id
        {
            get { return "201303051448262_ParentId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
